### ISSUE TITLE
About recommended_buffered_ether

### ISSUE THREAD

**Issue by RayLvv** [lidofinance/depositor-bot#129]
Hello, we found that `recommended_buffered_ether` in depositor bot can be less than 32 ether, but lido require more than 32 ether to deposit. Will it waste gas if it tries to deposit in this case？Source code here

        current_gas_fee = web3.eth.get_block('pending').baseFeePerGas
        
        # Lido contract buffered ether check
        buffered_ether = LidoInterface.getBufferedEther(block_identifier={"blockHash": self._current_block.hash.hex()})
        logger.info({'msg': 'Call `getBufferedEther()`.', 'value': buffered_ether})
        BUFFERED_ETHER.set(buffered_ether)

        recommended_buffered_ether = self.gas_fee_strategy.get_recommended_buffered_ether_to_deposit(current_gas_fee)

`self.gas_fee_strategy.get_recommended_buffered_ether_to_deposit` code here

    def get_recommended_buffered_ether_to_deposit(self, gas_fee):
        """Returns suggested minimum buffered ether to deposit"""
        apr = 0.044  # Protocol APR
        # ether/14 days : select sum(tr.value)/1e18 from ethereum."transactions" as tr
        # where tr.to = '\xae7ab96520DE3A18E5e111B5EaAb095312D7fE84'
        # and tr.block_time >= '2021-12-01' and tr.block_time < '2021-12-15' and tr.value < 600*1e18;
        a = 24  # ~ ether/hour
        keys_hour = a / 32
        p = 32 * 10**18 * apr / 365 / 24  # ~ Profit in hour
        cc = 378300  # gas constant for every deposit tx that should be paid
        multiply_constant = 1.5  # we will get profit with constant from 1 to 2, but the most profitable will be 1.5

        return sqrt(multiply_constant * cc * gas_fee * keys_hour / p) * 32 * 10**18

**Comment by RayLvv** [comment]
And we don't understand function `get_recommended_buffered_ether_to_deposit`

**Comment by F4ever** [comment]
Hi!
Since we spend quite a lot of money on gas, sometimes it is worth waiting a bit to deposit more keys at once in order to save gas.
This function calculates the optimal amount of ether that will pay off on the next deposit, based on the current gas rate.

Yeah, definitely we should do smth like:
```python
max(
    MIN_DEPOSIT_SIZE, #  32 eth
    self.get_recommended_buffered_ether_to_deposit(),
```
Thx for report.

**Comment by RayLvv** [comment]
OK, thanks for your reply. I have closed this issue just now.
